name: openups
base: core20 # the base snap is the execution environment for this snap
version: 'git' # just for humans, typically '1.2+git' or '1.3.2'
version-script: cat src/version.h | grep VERSION | cut -f 3 -d " " | tr -d '"'
summary: Control app for Mini-Box.com UPS products
description: Allows displaying the status and configuring the settings for all UPS products from Mini-Box.com. These include Open UPS, Open UPS2, NUC UPS and more.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # devmode # use 'strict' once you have the right plugs and slots

apps:
  openups:
    plugs: [raw-usb]
    command: usr/local/bin/openups
parts:
  openups:
    # See 'snapcraft plugins'
    plugin: cmake
    source: .
    source-type: local
    build-packages:
      - g++
      - make
      - libusb-0.1-4
      - libusb-dev
    stage-packages:
      - libusb-0.1-4